// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;
use diesel::prelude::*;
use serde::Serialize;

use crate::schema::users;

#[derive(Queryable, Debug, Serialize)]
#[diesel(table_name = users)]
pub struct User {
    pub id: i32,
    pub google_id: String,
    pub email: String,
    pub name: String,
    pub avatar_url: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Insertable)]
#[diesel(table_name = users)]
pub struct NewUser<'a> {
    pub google_id: &'a str,
    pub email: &'a str,
    pub name: &'a str,
    pub avatar_url: Option<&'a str>,
}
